services:
  bazel-example:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          UID: "${UID:-1000}"
          USER: "${USER:-root}"
      target: base
    container_name: bazel-minimum-example-container
    image: not/pushed/bazel/minimum-example:${DOCKER_IMAGE_HASH:-latest}-${USER:-root}
    volumes:
      - .:/workspace
    working_dir: /workspace
    user: "${USER}"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    entrypoint: /bin/bash